### ISSUE TITLE
DFD Comments Feb 15

### ISSUE THREAD

**Issue by germonprez** [sjacobs7/ISQA3420#10]
Hey, 

Here are a few comments: 

1) Scan Results and Vulnerability Results should go back to the developer 
2) Data Request and Data Response are pretty vague names. It would be better to be more precise in your naming of these
3) The Developer should also be able to do the Data Request and Data Response that you have from the Manager (renamed too)
4) The CRUD process is OK. It is not terribly detailed and if you have time, I'd recommend that you make it a bit more granular. 

MG

**Comment by sjacobs7** [comment]
Thanks Professor Germonprez. These changes have been made with the exception of number 4, which I left for the time being as CRUD for simplicity.
